=== openpreserve/fido/fido/conf/fido-formats.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Usage of DC has been based on these references:
  http://dublincore.org/documents/usageguide/elements.shtml
  http://dublincore.org/documents/usageguide/qualifiers.shtml
  http://www.dublincore.org/documents/dc-xml-guidelines/
-->
<xs:schema elementFormDefault="qualified" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema"  
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:dcterms="http://purl.org/dc/terms/">
  <xs:import namespace="http://purl.org/dc/elements/1.1/" schemaLocation="dc.xsd"/>
  <xs:import namespace="http://purl.org/dc/terms/" schemaLocation="dcterms.xsd"/>
<!-- http://www.dublincore.org/schemas/xmls/qdc/2003/04/02/dcterms.xsd" -->
  <xs:element name="formats">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="format"/>
      </xs:sequence>
      <xs:attribute name="version" type="xs:decimal" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="format">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="1" ref="puid"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="mime"/>
        <xs:element minOccurs="0" ref="container"/>
        <xs:element maxOccurs="1" minOccurs="1" ref="name"/>
        <xs:element maxOccurs="1" minOccurs="0" name="version" type="xs:string"/>
        <xs:element minOccurs="0" name="alias"  type="xs:string"/>
        <xs:element maxOccurs="1" minOccurs="0" ref="pronom_id"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="extension"/>
        <xs:element maxOccurs="1" minOccurs="0" name="apple_uti" type="xs:string"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="has_priority_over"/>
        <xs:element maxOccurs="unbounded" ref="signature"/>
        <xs:element minOccurs="0" ref="note"/>
        <xs:element maxOccurs="1" ref="details"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="mime" type="xs:string"/>
  <xs:element name="puid" type="xs:string"/>
  <xs:element name="container" type="container_type"/>
  <xs:element name="pronom_id" type="xs:integer"/>
  <xs:element name="extension" type="xs:string"/>
  <xs:element name="has_priority_over" type="xs:string"/>
  <xs:element name="signature">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="note" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element maxOccurs="unbounded" ref="pattern"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="note" type="xs:string"/>
  <xs:element name="pattern">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="position"/>
        <xs:element ref="pronom_pattern" minOccurs="0"/>
        <xs:element ref="regex" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="position" type="position_type"/>
  <xs:element name="pronom_pattern" type="xs:string"/>
  <xs:element name="regex" type="xs:string"/>
  <xs:element name="name" type="xs:string"/>
  <xs:simpleType name="position_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="BOF"/>
      <xs:enumeration value="EOF"/>
      <xs:enumeration value="VAR"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="container_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="zip"/>
      <xs:enumeration value="tar"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="details">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="0" ref="dc:description"/>
        <xs:element maxOccurs="1" minOccurs="0" ref="dcterms:available"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="dc:creator"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="dcterms:publisher"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" name="is_supertype_of" type="xs:string"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" name="is_subtype_of" type="xs:string"/>
        <xs:element maxOccurs="1" minOccurs="0" name="content_type" type="xs:string"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="reference"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="example_file"/>
        <xs:element maxOccurs="1" minOccurs="0" ref="record_metadata"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="reference">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="0" name="type" type="xs:string"/>
        <xs:element maxOccurs="unbounded" ref="dc:any"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="example_file">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="dc:any"/>
        <xs:element minOccurs="1" ref="checksum"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="record_metadata">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="1" ref="status"/>
        <xs:element maxOccurs="unbounded" ref="dc:any"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="checksum">
    <xs:complexType mixed="true">
      <xs:sequence>
      </xs:sequence>
      <xs:attribute name="type" use="required">
       <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="md5"/>
          <xs:enumeration value="sha256"/>
        </xs:restriction>
       </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="status">
    <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="unknown"/>
          <xs:enumeration value="invalid"/>
          <xs:enumeration value="incomplete"/>
          <xs:enumeration value="stub"/>
          <xs:enumeration value="adequate"/>
          <xs:enumeration value="complete"/>
          <xs:enumeration value="superb"/>
          <xs:enumeration value="deprecated"/>
        </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="content_type">
    <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="raster"/>
          <xs:enumeration value="vector"/>
          <xs:enumeration value="image"/>
          <xs:enumeration value="spreadsheet"/>
          <xs:enumeration value="text"/>
          <xs:enumeration value="word-processed"/>
          <xs:enumeration value="page-description"/>
          <xs:enumeration value="audio"/>
          <xs:enumeration value="presentation"/>
          <xs:enumeration value="mark-up"/>
          <xs:enumeration value="database"/>
          <xs:enumeration value="video"/>
          <xs:enumeration value="email"/>
          <xs:enumeration value="other"/>
        </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>

=== openpreserve/fido/fido/conf/format_extensions.xml
<?xml version="1.0"?>
<formats xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.2" xsi:noNamespaceSchemaLocation="fido-formats.xsd">
  <format>
    <puid>fido-fmt/189.word</puid>
    <name>Microsoft Office Open XML - Word</name>
    <extension>docx</extension>
    <has_priority_over>x-fmt/263</has_priority_over>
    <has_priority_over>fmt/189</has_priority_over>
    <signature>
      <name>Microsoft Office Open XML - Word</name>
      <pattern>
        <position>BOF</position>
        <regex>(?s)\APK\x03\x04</regex>
      </pattern>
      <pattern>
        <position>BOF</position>
        <regex>(?s)\A.{30}\[Content_Types\]\.xml \xa2</regex>
      </pattern>
      <pattern>
        <position>EOF</position>
        <regex>(?s)\x00\x00word/.{1,20}\.xmlPK\x01\x02\x2d.{0,2000}\Z</regex>
      </pattern>
    </signature>
  </format>
  <format>
    <puid>fido-fmt/189.xl</puid>
    <name>Microsoft Office Open XML - Excel</name>
    <extension>xlsx</extension>
    <has_priority_over>x-fmt/263</has_priority_over>
    <has_priority_over>fmt/189</has_priority_over>
    <signature>
      <name>Microsoft Office Open XML - Excel</name>
      <pattern>
        <position>BOF</position>
        <regex>(?s)\APK\x03\x04</regex>
      </pattern>
      <pattern>
        <position>BOF</position>
        <regex>(?s)\A.{30}\[Content_Types\]\.xml \xa2</regex>
      </pattern>
      <pattern>
        <position>EOF</position>
        <regex>(?s)\x00xl/.{1,20}\.xmlPK\x01\x02\x2d.{0,2000}\Z</regex>
      </pattern>
    </signature>
  </format>
  <format>
    <puid>fido-fmt/189.ppt</puid>
    <name>Microsoft Office Open XML - Powerpoint</name>
    <extension>pptx</extension>
    <has_priority_over>x-fmt/263</has_priority_over>
    <has_priority_over>fmt/189</has_priority_over>
    <signature>
      <name>Microsoft Office Open XML - Powerpoint</name>
      <pattern>
        <position>BOF</position>
        <regex>(?s)\APK\x03\x04</regex>
      </pattern>
      <pattern>
        <position>BOF</position>
        <regex>(?s)\A.{30}\[Content_Types\]\.xml \xa2</regex>
      </pattern>
      <pattern>
        <position>EOF</position>
        <!-- ppt/presentation.xml might be better, but it can be far from the end. -->
        <regex>(?s)\x00ppt/.{1,20}\.xmlPK\x01\x02\x2d.{0,2000}\Z</regex>
      </pattern>
    </signature>
  </format>
  <format>
    <puid>fmt/134</puid>
    <mime>audio/mpeg</mime>
    <name>MPEG 1/2 Audio Layer 3 - fido update</name>
    <pronom_id>687</pronom_id>
    <extension>mp3</extension>
    <signature>
      <name>MPEG-1/2 Audio Layer 3</name>
      <note>The pronom signatures for fmt/134 were horrendous.  This is an attempt to consolidate several
                  nearly identical patterns into one.  It is not clear if they should be BOF or EOF or both.
                  Regularly-spaced frame headers should always be discoverable near EOF. An ID3v1
                tag of up to 355 bytes may be present at EOF.</note>
      <pattern>
        <position>EOF</position>
        <regex>(?s)\xff[\xfa\xfb\xf2\xf3][\x10-\xeb].{46,1439}\xff[\xfa\xfb\xf2\xf3][\x10-\xeb].{46,1439}\Z</regex>
      </pattern>
      <pattern>
        <position>BOF</position>
        <pronom_pattern>494433</pronom_pattern>
        <regex>(?s)\AID3</regex>
      </pattern>
    </signature>
  </format>
  <format>
    <puid>fido-x-fmt/384</puid>
    <mime>video/quicktime</mime>
    <name>Quicktime</name>
    <extension>mov</extension>
    <signature>
      <name>QuickTime</name>
      <note>Simple addition to cover the case in the fido test suite.  Needs research to correct and merge with x-fmt/384</note>
      <pattern>
        <position>BOF</position>
        <regex>(?s)\A\x00{3} ftypqt.{0,25}qt.{0,20}moov.{4}mvhd</regex>
      </pattern>
    </signature>
  </format>
  <format>
    <puid>fmt/40</puid>
    <mime>application/msword</mime>
    <name>Microsoft Word for Windows Document</name>
    <pronom_id>690</pronom_id>
    <extension>doc</extension>
    <has_priority_over>fmt/111</has_priority_over>
    <signature>
      <name>Microsoft Word for Windows 97 - 2002</name>
      <note>2010.12 - AF: Some of my test files do not have 8.0, but 97-2003.</note>
      <note>Compound document header + WordDocument user stream + version number</note>
      <pattern>
        <position>BOF</position>
        <pronom_pattern>D0CF11E0A1B11AE1{20}FEFF</pronom_pattern>
        <regex>(?s)\A\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1.{20}\xfe\xff</regex>
      </pattern>
      <pattern>
        <position>VAR</position>
        <pronom_pattern>57006F007200640044006F00630075006D0065006E007400{42}02(00|01)</pronom_pattern>
        <regex>(?s)W\x00o\x00r\x00d\x00D\x00o\x00c\x00u\x00m\x00e\x00n\x00t\x00.{42}\x02(?:\x00|\x01)</regex>
      </pattern>
      <pattern>
        <position>VAR</position>
        <pronom_pattern>4D6963726F736F667420576F7264(20382E30|20392E30|2031302E30|2D446F6B756D656E74)</pronom_pattern>
        <regex>(?s)Microsoft (?:Office Word|Word)(?: 8\.0| 9\.0| 10\.0|-Dokument| 97-2003)</regex>
      </pattern>
    </signature>
  </format>
  <!-- RTF -->
  <format>
    <puid>fmt/45</puid>
    <mime>application/rtf</mime>
    <mime>text/rtf</mime>
    <name>Rich Text Format</name>
    <pronom_id>626</pronom_id>
    <extension>rtf</extension>
    <signature>
      <name>RTF 1.0 - 1.4 (generic)</name>
      <note>Pronom has FIVE RTF formats (fmt/45-49) with identical patterns that don't match my sample.</note>
      <pattern>
        <position>BOF</position>
        <pronom_pattern>7B5C7274(66|6631)5C(616E7369|6D6163|7063|706361)</pronom_pattern>
        <regex>(?s)\A\{\\rt(?:f|f1)\\(?:adeflang1025|ansi|mac|pc|pca)</regex>
      </pattern>
    </signature>
  </format>
  <format>
    <puid>fmt/46</puid>
    <mime>application/rtf</mime>
    <mime>text/rtf</mime>
    <name>Rich Text Format</name>
    <pronom_id>627</pronom_id>
    <extension>rtf</extension>
    <signature>
      <name>RTF 1.0 - 1.4 (generic)</name>
      <note>\rtf control word</note>
      <pattern>
        <position>BOF</position>
        <pronom_pattern>7B5C7274(66|6631)5C(616E7369|6D6163|7063|706361)</pronom_pattern>
        <!-- HACK.  This should fail any non-empty buffer. All of the RTF signatures have the same pattern.
             This version of fido does not have a 'delete' method.
         -->
        <regex>\A\Z</regex>
      </pattern>
    </signature>
  </format>
  <format>
    <puid>fmt/47</puid>
    <mime>application/rtf</mime>
    <mime>text/rtf</mime>
    <name>Rich Text Format</name>
    <pronom_id>628</pronom_id>
    <extension>rtf</extension>
    <signature>
      <name>RTF 1.0 - 1.4 (generic)</name>
      <note>\rtf control word</note>
      <pattern>
        <position>BOF</position>
        <pronom_pattern>7B5C7274(66|6631)5C(616E7369|6D6163|7063|706361)</pronom_pattern>
        <regex>\A\Z</regex>
      </pattern>
    </signature>
  </format>
  <format>
    <puid>fmt/48</puid>
    <mime>application/rtf</mime>
    <mime>text/rtf</mime>
    <name>Rich Text Format</name>
    <pronom_id>629</pronom_id>
    <extension>rtf</extension>
    <signature>
      <name>RTF 1.0 - 1.4 (generic)</name>
      <note>\rtf control word</note>
      <pattern>
        <position>BOF</position>
        <pronom_pattern>7B5C7274(66|6631)5C(616E7369|6D6163|7063|706361)</pronom_pattern>
        <regex>\A\Z</regex>
      </pattern>
    </signature>
  </format>
  <format>
    <puid>fmt/49</puid>
    <mime>application/rtf</mime>
    <mime>text/rtf</mime>
    <name>Rich Text Format</name>
    <pronom_id>630</pronom_id>
    <extension>rtf</extension>
    <signature>
      <name>RTF 1.0 - 1.4 (generic)</name>
      <note>\rtf control word</note>
      <pattern>
        <position>BOF</position>
        <pronom_pattern>7B5C7274(66|6631)5C(616E7369|6D6163|7063|706361)</pronom_pattern>
        <regex>\A\Z</regex>
      </pattern>
    </signature>
  </format>
  <format>
<!-- 
* Intalev Cayra Mindmap file format
* added by <maurice.de.rooij@nationaalarchief.nl> (NANETH)
* as part of the DEV8DAY OPF format-challenge on 16/17 february 2011
-->
    <puid>fido-fmt/666.cayra</puid>
    <name>Intalev Cayra Mindmap file</name>
    <extension>cayra</extension>
    <has_priority_over>x-fmt/263</has_priority_over>
    <signature>
      <name>Intalev Cayra Mindmap file</name>
      <pattern>
        <position>BOF</position>
        <regex>(?s)\APK\x03\x04</regex>
      </pattern>
      <pattern>
        <position>BOF</position>
        <regex>(?s)\A.{30}bin\/[a-z0-9]{8}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-z0-9]{12}\x20\xa2</regex>
      </pattern>
      <pattern>
        <position>EOF</position>
        <regex>(?s)\[Content_Types\]\.xmlPK\x05\x06\x00.{17}\Z</regex>
      </pattern>
    </signature>
  </format>
</formats>
</formats>

=== openpreserve/fido/fido/conf/format_extension_template_0.2.xml
<?xml version="1.0"?>
<formats xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.2" xsi:noNamespaceSchemaLocation="fido-formats.xsd">
  <format>
    <puid>fido-fmt/189.word</puid>
    <name>Microsoft Office Open XML - Word</name>
    <extension>docx</extension>
    <has_priority_over>x-fmt/263</has_priority_over>
    <has_priority_over>fmt/189</has_priority_over>
    <signature>
      <name>Microsoft Office Open XML - Word</name>
      <pattern>
        <position>BOF</position>
        <regex>(?s)\APK\x03\x04</regex>
      </pattern>
      <pattern>
        <position>BOF</position>
        <regex>(?s)\A.{30}\[Content_Types\]\.xml \xa2</regex>
      </pattern>
      <pattern>
        <position>EOF</position>
        <regex>(?s)\x00\x00word/.{1,20}\.xmlPK\x01\x02\x2d.{0,2000}\Z</regex>
      </pattern>
    </signature>
  </format>
</formats>
